spring:
  application:
    name: scouting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scouting?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: scout
    password: Pa$$word4
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 15
      connection-init-sql: select 1
    tomcat:
      jmx-enabled: false
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  groovy:
    template:
      check-template-location: false
server:
  compression:
    enabled: true
  port: 8080
  servlet:
    application-display-name: scouting
    context-path: /scouting
